name: Morgan dev Provider
on:
  push:
    branches: [morgan]
    paths:
      - "provider/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build web
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Get branch name
        uses: tj-actions/branch-names@v7
        id: branch-name

      - name: Run yarn install
        run: yarn
        working-directory: ./provider

      - name: Build
        run: yarn build:${{ steps.branch-name.outputs.current_branch }}
        working-directory: ./provider

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to S3 bucket
        working-directory: ./provider
        run: aws s3 sync ./build/ s3://${{ secrets.MORGAN_PROVIDER_S3BUCKET }} --delete

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.MORGAN_PROVIDER_DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "ap-southeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
