name: Prod Provider
on:
  push:
    branches: [prod]
    paths:
      - "provider/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: dogepay
            s3_bucket: dogepay-provider
            cloudfront_dist: E27LFAS299L91R
          - name: sinopay
            s3_bucket: sinopay-provider
            cloudfront_dist: E2ZGZJXWG144YL
          - name: sinopayold
            s3_bucket: sinopay-old-provider
            cloudfront_dist: E2ZGZJXWG144YL
          - name: snpay
            s3_bucket: snpay-provider
            cloudfront_dist: EWPVJ15LRC1ZC
          - name: powerpay
            s3_bucket: powerpay-provider
            cloudfront_dist: E38JNWI3SSFRG8
          - name: ehpay
            s3_bucket: ehpay-provider
            cloudfront_dist: E374NNNCS20T0Q
          - name: jaxoncashier
            s3_bucket: jaxoncashier-provider
            cloudfront_dist: E6VRPEHJREKZR

    name: Build and Deploy ${{ matrix.app.name }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Get branch name
        uses: tj-actions/branch-names@v7
        id: branch-name

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Run yarn install
        run: yarn
        working-directory: ./provider

      - name: Build ${{ matrix.app.name }}
        run: yarn build:${{ matrix.app.name }}
        working-directory: ./provider

      - name: Deploy to ${{ matrix.app.name }} S3 bucket
        working-directory: ./provider
        run: aws s3 sync ./build/ s3://${{ matrix.app.s3_bucket }} --delete

      - name: Invalidate ${{ matrix.app.name }} CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ matrix.app.cloudfront_dist }}
          PATHS: "/*"
          AWS_REGION: "ap-southeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
