name: Prod Merchant
on:
  push:
    branches: [prod]
    paths:
      - "merchant/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: dogepay
            s3_bucket: dogepay-merchant
            distribution: E2JIPV0TVI6LL5
          - name: sinopay
            s3_bucket: sinopay-merchant
            distribution: E1HUC37C3PJ7OC
          - name: sinopayold
            s3_bucket: sinopay-old-merchant
            distribution: E13A9A3OS7GBE
          - name: snpay
            s3_bucket: snpay-merchant
            distribution: EIBXC48I3UBO
          - name: powerpay
            s3_bucket: powerpay-merchant
            distribution: E1DNF6ENGP1GSZ
          - name: ehpay
            s3_bucket: ehpay-merchant
            distribution: EZ7LURFUZI62H
          - name: jaxoncashier
            s3_bucket: jaxoncashier-merchant
            distribution: E3UC63E9AEMYCC

    name: Build and deploy ${{ matrix.app.name }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Get branch name
        uses: tj-actions/branch-names@v7
        id: branch-name

      - name: Run yarn install
        run: yarn
        working-directory: ./merchant

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Build
        run: yarn build:${{ matrix.app.name }}
        working-directory: ./merchant

      - name: Deploy to S3 bucket
        working-directory: ./merchant
        run: aws s3 sync ./build/ s3://${{ matrix.app.s3_bucket }} --delete

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ matrix.app.distribution }}
          PATHS: "/*"
          AWS_REGION: "ap-southeast-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
